api:
  build: ./api
  ports:
   - "8000:8000"
  command: cabal run api

app:
  build: ./app
  links:
   - api
  ports:
   - "8080:8080"
  command: nginx

test:
  build: ./spec
  links:
    - api
  command: cabal run spec
