api:
  build: ./api
  links:
   - db
  ports:
   - "8000:8000"
  command: cabal run

app:
  build: ./app
  links:
   - api
  ports:
   - "8080:8080"
  command: nginx

db:
  image: mongo

test:
  build: ./test
  links:
    - api
    - db
  command: cabal run
