api:
  build: ./api
  ports:
   - "8000:8000"
  command: cabal run api

client:
  build: ./client

proxy:
  image: tgolson/nginx-spa
  ports:
    - "8080:8080"
  volumes_from:
    - client
  links:
    - api

integrationtest:
  build: ./integration-test
  links:
    - api
  command: cabal run integration-test
